
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./dist:/app/dist
    environment:
      DB_HOST: db
    command: npm start
  db:
    image: mongo:6.0
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: